### PR TITLE
GlassVaseFlowers

### PR DESCRIPTION
**Pull request by echadwick-artist**
Adding a new model, to showcase the differences between alpha blending and transmission/volume for glass surfaces.

Hopefully this will help with the production of the upcoming Transmission tutoriual video.

screenshot_large
(Updated screenshot to match latest commit)

### CODE REVIEW

**Comment by echadwick-artist** [comment]
Another lighting setup, maybe better? Using the Studio Neutral environment.

image

**Comment by DRx3D** [comment]
Is this model schedule for inclusion in a video?

**Comment by echadwick-artist** [comment]
Yes, this model is listed in the draft6 script for transmission.

**Comment by DRx3D** [comment]
Approved for merging into Development repo

**Pull request merged**
